name: Nexascale Actions Yml File

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]

jobs:
  nexascale-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout my repo

      - name: Setup nodejs on ubuntu
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node dependencies
        run: npm install

      - name: Build Nestjs application
        run: npm run build

      - name: Test Nestjs application
        run: npm run test